apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tc-pipeline
spec:
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
    - name: repo-url
      type: string

  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws

  tasks:

    # 0️⃣ CLONE REPO
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: main

    # 1️⃣ NPM INSTALL
    - name: npminstall
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - clone

    # 2️⃣ JASMINE TESTS
    - name: tests
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - npminstall

    # 3️⃣ BUILD IMAGE
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      params:
        - name: IMAGE
          value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"
      runAfter:
        - tests