apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws

  tasks:

    # 1️⃣ NPM INSTALL
    - name: npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: npm
      runAfter:
        - clone

    # 2️⃣ JASMINE TESTS
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: jasmine
      runAfter:
        - npminstall

    # 3️⃣ BUILD IMAGE (ClusterTask)
    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"
      runAfter:
        - tests